### ISSUE TITLE
Okteto fails when integrated with pycharm

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#1293]
**Describe the bug**
Opening a terminal in pycharm 2020.3 fails after configuring the interpreter to use an Okteto dev env.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.10.1
- pycharm 2020.3

**Comment by jungsukk83** [comment]
1. Followed instruction in the [article](https://okteto.com/blog/remote-development-environments-with-pycharm/) with modified `okteto.yml`
``` yaml
name: test
image: okteto/python:3
command: bash
volumes:
- /root/.cache/pip
sync:
- .:/usr/src/app
forward:
- 8080:8080
reverse:
- 9000:9000
remote: 2222
```

2. Successfully completed to "_Use your Remote Environment as an Interpreter_" steps
3. Launched Python Console from PyCharm but it failed with following error message
> No details...
```
Error:Console process terminated with error:
```
4. no error in `$HOME/.okteto/okteto.log`
5. Found error from ` ~/Library/Logs/PyCharm2019.3/idea.log`
> followings are exact copy, log includes ```	... 23 more```
```
2021-02-23 20:34:09,022 [1006332]   WARN - console.PydevConsoleRunnerImpl - Error running console
com.intellij.execution.ExecutionException: Console process terminated with error:

	at com.jetbrains.python.remote.console.PythonConsoleSshProcessCreatorBase.createRemoteConsoleProcess(pythonConsoleSshProcessCreators.kt:67)
	at com.jetbrains.python.console.PythonConsoleRemoteProcessCreatorKt$createRemoteConsoleProcess$$inlined$map$lambda$1.process(PythonConsoleRemoteProcessCreator.kt:96)
	at com.intellij.remote.RemoteConnectionCredentialsWrapper.switchType(RemoteConnectionCredentialsWrapper.java:96)
	at com.jetbrains.python.remote.PyRemoteSdkAdditionalData.switchOnConnectionType(PyRemoteSdkAdditionalData.java:115)
	at com.jetbrains.python.console.PythonConsoleRemoteProcessCreatorKt.createRemoteConsoleProcess(PythonConsoleRemoteProcessCreator.kt:111)
	at com.jetbrains.python.console.PydevConsoleRunnerImpl.createProcess(PydevConsoleRunnerImpl.java:391)
	at com.jetbrains.python.console.PydevConsoleRunnerImpl.initAndRun(PydevConsoleRunnerImpl.java:519)
	at com.jetbrains.python.console.PydevConsoleRunnerImpl.access$1800(PydevConsoleRunnerImpl.java:106)
	at com.jetbrains.python.console.PydevConsoleRunnerImpl$2.run(PydevConsoleRunnerImpl.java:269)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.intellij.execution.ExecutionException: Console process terminated with error:

	at com.jetbrains.python.console.PydevConsoleRunnerImpl.readInt(PydevConsoleRunnerImpl.java:482)
	at com.jetbrains.python.console.PydevConsoleRunnerImpl.getRemotePortFromProcess(PydevConsoleRunnerImpl.java:446)
	at com.jetbrains.python.remote.console.PythonConsoleSshProcessCreatorBase.createRemoteConsoleProcess(pythonConsoleSshProcessCreators.kt:52)
	... 23 more
```

**Comment by rberrelleza** [comment]
@jungsukk83 this is fixed on the posts, please let me know if you still this?
