### ISSUE TITLE
okteto context create throws a nullref if $HOME/.okteto is empty or missing

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2116]
**Describe the bug**
okteto context create throws a nullref if $HOME/.okteto is empty

```
$ rm -rf $HOME/.okteto
$ okteto context create

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/okteto/okteto/cmd/context.CreateCMD.func1(0x140011e2000, {0x104323e68, 0x0, 0x0})
	github.com/okteto/okteto/cmd/context/create.go:69 +0x248
github.com/spf13/cobra.(*Command).execute(0x140011e2000, {0x104323e68, 0x0, 0x0})
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x668
github.com/spf13/cobra.(*Command).ExecuteC(0x140011daa00)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x410
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	github.com/okteto/okteto/main.go:126 +0x860

```
**Desktop (please complete the following information):**

- OS: macOS
- Version 1.14.10

**Comment by rberrelleza** [comment]
The same doesn't happen if I type `okteto context`

**Comment by jmacelroy** [comment]
@jLopezbarb If i'm not mistaken we had a similar issue that was fixed for `okteto context`. If so we should be able to generalize that fix better and have it apply to any context * cmd?
