### ISSUE TITLE
The user defined in a Dockerfile can't create directories inside of a volume created during stack creation

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2119]
**Describe the bug**
The user defined in a Dockerfile can't create directories inside of a volume created during stack creation. From a high-level analysis it seems like the volumes we create during deployment are owned by 'root'. While normally this is not an issue, this causes problems if a) the user of the main process is not root AND b) the user tries to create files or folders in said volume. A typical scenario for this is when creating a file for logging.

**To Reproduce**

1. Deploy https://github.com/codeforequity-at/botium-speech-processing
2. See the status of the frontend service. 

**Expected behavior**
The user defined in the dockerfile should be able to read/write inside the volumes we create.

**Desktop (please complete the following information):**

- OS: macOS
- Version 1.4.10

**Comment by Shubhamjugran** [comment]
Everything runs fine on the local machine.

docker-compose logs are as follows 👍 

stt-en_1    | 2022-01-08 14:32:52,139 CRIT Supervisor running as root (no user in config file)
frontend_1  | > botium-speech-processing-frontend@1.0.0 start-dist /app
frontend_1  | > node -r dotenv-flow/config ./src/server.js
frontend_1  |
stt-en_1    | 2022-01-08 14:32:52,140 WARN Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
stt-en_1    | Unlinking stale socket /var/run/supervisor.sock
stt-en_1    | 2022-01-08 14:32:52,460 INFO RPC interface 'supervisor' initialized
stt-en_1    | 2022-01-08 14:32:52,460 CRIT Server 'unix_http_server' running without any HTTP authentication checking
stt-en_1    | 2022-01-08 14:32:52,461 INFO supervisord started with pid 1
stt-en_1    | 2022-01-08 14:32:53,465 INFO spawned: 'worker1' with pid 10
stt-en_1    | 2022-01-08 14:32:53,469 INFO spawned: 'worker2' with pid 11
stt-en_1    | 2022-01-08 14:32:53,473 INFO spawned: 'master' with pid 12
stt-en_1    | 2022-01-08 14:32:55,436 INFO success: worker1 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
stt-en_1    | 2022-01-08 14:32:55,436 INFO success: worker2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
stt-en_1    | 2022-01-08 14:32:55,436 INFO success: master entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
frontend_1  | dotenv-flow: "BOTIUM_SPEECH_PROVIDER_TTS" is already defined in `process.env` and will not be overwritten
frontend_1  | dotenv-flow: "BOTIUM_SPEECH_PROVIDER_STT" is already defined in `process.env` and will not be overwritten
frontend_1  | WARNING: BOTIUM_API_TOKENS not set, all clients will be accepted
frontend_1  | Botium Speech Processing Frontend service running on port 56000
frontend_1  | Swagger UI available at /
frontend_1  | Swagger definition available at /swagger.json
frontend_1  |
frontend_1  | > botium-speech-processing-frontend@1.0.0 start-dist /app
frontend_1  | > node -r dotenv-flow/config ./src/server.js
frontend_1  |
frontend_1  | dotenv-flow: "BOTIUM_SPEECH_PROVIDER_TTS" is already defined in `process.env` and will not be overwritten
frontend_1  | dotenv-flow: "BOTIUM_SPEECH_PROVIDER_STT" is already defined in `process.env` and will not be overwritten
frontend_1  | WARNING: BOTIUM_API_TOKENS not set, all clients will be accepted
frontend_1  | Botium Speech Processing Frontend service running on port 56000
frontend_1  | Swagger UI available at /
frontend_1  | Swagger definition available at /swagger.json

**Comment by pchico83** [comment]
@jLopezbarb were you able to repro the issue? I thought we were creating the volume with 777 permissions to avoid this problem

**Comment by pchico83** [comment]
@Shubhamjugran does it work if you define the volume:
https://github.com/codeforequity-at/botium-speech-processing/blob/master/frontend/Dockerfile#L13
after switching to the node user?
https://github.com/codeforequity-at/botium-speech-processing/blob/master/frontend/Dockerfile#L18

**Comment by Shubhamjugran** [comment]
I tried what you said and still have these errors. You can try too maybe I'm doing it wrong. Updated Dockerfile https://github.com/Shubhamjugran/botium-speech-processing/tree/master/frontend 

2022-01-12 08:36:57.00 UTCfrontend-86bff98446-m4zfl[pod-event]Successfully pulled image "registry.cloud.okteto.net/voice-shubhamjugran/botium-speech-processing-frontend:okteto-with-volume-mounts" in 302.350138ms
2022-01-12 08:36:58.27 UTCfrontend-86bff98446-m4zflfrontend
2022-01-12 08:36:58.27 UTCfrontend-86bff98446-m4zflfrontend> botium-speech-processing-frontend@1.0.0 start-dist /app
2022-01-12 08:36:58.27 UTCfrontend-86bff98446-m4zflfrontend> node -r dotenv-flow/config ./src/server.js
2022-01-12 08:36:58.27 UTCfrontend-86bff98446-m4zflfrontend
2022-01-12 08:36:58.35 UTCfrontend-86bff98446-m4zflfrontenddotenv-flow: "BOTIUM_SPEECH_PROVIDER_TTS" is already defined in `process.env` and will not be overwritten
2022-01-12 08:36:58.35 UTCfrontend-86bff98446-m4zflfrontenddotenv-flow: "BOTIUM_SPEECH_PROVIDER_STT" is already defined in `process.env` and will not be overwritten
2022-01-12 08:36:59.31 UTCfrontend-86bff98446-m4zflfrontend/app/node_modules/mkdirp/lib/mkdirp-native.js:35
2022-01-12 08:36:59.31 UTCfrontend-86bff98446-m4zflfrontend throw er
2022-01-12 08:36:59.31 UTCfrontend-86bff98446-m4zflfrontend ^
2022-01-12 08:36:59.31 UTCfrontend-86bff98446-m4zflfrontend
2022-01-12 08:36:59.31 UTCfrontend-86bff98446-m4zflfrontendError: EACCES: permission denied, mkdir '/app/resources/.cache/stt'
2022-01-12 08:36:59.31 UTCfrontend-86bff98446-m4zflfrontend at Object.mkdirSync (fs.js:987:3)
2022-01-12 08:36:59.31 UTCfrontend-86bff98446-m4zflfrontend at mkdirpNativeSync (/app/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
2022-01-12 08:36:59.31 UTCfrontend-86bff98446-m4zflfrontend at Function.mkdirpSync [as sync] (/app/node_modules/mkdirp/index.js:21:7)
2022-01-12 08:36:59.31 UTCfrontend-86bff98446-m4zflfrontend at Object.<anonymous> (/app/src/routes.js:30:26)
2022-01-12 08:36:59.31 UTCfrontend-86bff98446-m4zflfrontend at Module._compile (internal/modules/cjs/loader.js:1063:30)
2022-01-12 08:36:59.31 UTCfrontend-86bff98446-m4zflfrontend at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2022-01-12 08:36:59.31 UTCfrontend-86bff98446-m4zflfrontend at Module.load (internal/modules/cjs/loader.js:928:32)
2022-01-12 08:36:59.31 UTCfrontend-86bff98446-m4zflfrontend at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2022-01-12 08:36:59.31 UTCfrontend-86bff98446-m4zflfrontend at Module.require (internal/modules/cjs/loader.js:952:19)
2022-01-12 08:36:59.31 UTCfrontend-86bff98446-m4zflfrontend at require (internal/modules/cjs/helpers.js:88:18) {
2022-01-12 08:36:59.31 UTCfrontend-86bff98446-m4zflfrontend errno: -13,
2022-01-12 08:36:59.31 UTCfrontend-86bff98446-m4zflfrontend syscall: 'mkdir',
2022-01-12 08:36:59.31 UTCfrontend-86bff98446-m4zflfrontend code: 'EACCES',
2022-01-12 08:36:59.31 UTCfrontend-86bff98446-m4zflfrontend path: '/app/resources/.cache/stt'
2022-01-12 08:36:59.31 UTCfrontend-86bff98446-m4zflfrontend}
2022-01-12 08:36:59.33 UTCfrontend-86bff98446-m4zflfrontendnpm ERR! code ELIFECYCLE
2022-01-12 08:36:59.33 UTCfrontend-86bff98446-m4zflfrontendnpm ERR! errno 1
2022-01-12 08:36:59.33 UTCfrontend-86bff98446-m4zflfrontendnpm ERR! botium-speech-processing-frontend@1.0.0 start-dist: `node -r dotenv-flow/config ./src/server.js`
2022-01-12 08:36:59.33 UTCfrontend-86bff98446-m4zflfrontendnpm ERR! Exit status 1
2022-01-12 08:36:59.33 UTCfrontend-86bff98446-m4zflfrontendnpm ERR! 
2022-01-12 08:36:59.33 UTCfrontend-86bff98446-m4zflfrontendnpm ERR! Failed at the botium-speech-processing-frontend@1.0.0 start-dist script.
2022-01-12 08:36:59.33 UTCfrontend-86bff98446-m4zflfrontendnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2022-01-12 08:36:59.34 UTCfrontend-86bff98446-m4zflfrontend
2022-01-12 08:36:59.34 UTCfrontend-86bff98446-m4zflfrontendnpm ERR! A complete log of this run can be found in:
2022-01-12 08:36:59.34 UTCfrontend-86bff98446-m4zflfrontendnpm ERR! /home/node/.npm/_logs/2022-01-12T08_36_59_338Z-debug.log
