### ISSUE TITLE
nilref when the `okteto.yml` is malformed yaml

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#2685]
**Describe the bug**
when I ran `okteto up` on this manifest:
```
name: frontend
image: image: okteto.dev/frontend-dev
command: bash
sync:
  - .:/usr/src/app
 ```

it failed with this:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x106106bbc]

goroutine 1 [running]:
github.com/okteto/okteto/cmd/up.Up.func1(0x14001171180?, {0x1086b5c20, 0x0, 0x0})
        github.com/okteto/okteto/cmd/up/up.go:130 +0x50c
github.com/spf13/cobra.(*Command).execute(0x14001171180, {0x1086b5c20, 0x0, 0x0})
        github.com/spf13/cobra@v1.3.0/command.go:856 +0x4c4
github.com/spf13/cobra.(*Command).ExecuteC(0x14001162f00)
        github.com/spf13/cobra@v1.3.0/command.go:974 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
        github.com/okteto/okteto/main.go:135 +0x6a8

```
**Additional context**
This happened on the 2.3-rc1 build

**Comment by pchico83** [comment]
@jLopezbarb updated

**Comment by AgustinRamiroDiaz** [comment]
It's already fixed in the tip of master. This is the error message
```
 lokteto up
 x  Yaml: line 2: mapping values are not allowed in this context
 ```
