### ISSUE TITLE
Deploy fails with a runtime-error - "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by hagaym** [okteto/okteto#3293]
**Describe the bug**
After several days of working with Okteto CLI successfully (deploying, up-ing, etc.), suddenly getting the following error upon deploy command:
```
hmyr@MBP-HMYR cdp % okteto deploy
 i  Using hagaym @ yotpo.okteto.dev as context
 i  Build section is not defined in your okteto manifest
 i  Running 'okteto pipeline deploy --skip-if-exists --repository https://github.com/YotpoLtd/okteto-kafka.git'
 !  Initializing context with the value of OKTETO_TOKEN environment variable
 i  Using hagaym @ yotpo.okteto.dev as context
 ✓  Skipping repository 'okteto-kafka' because it's already deployed
 i  Running 'okteto deploy --file .okteto/docker-compose.yml --name cdp'
 !  Initializing context with the value of OKTETO_TOKEN environment variable
 i  Using hagaym @ yotpo.okteto.dev as context
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0xf8 pc=0x1024a2e34]

goroutine 21 [running]:
github.com/okteto/okteto/pkg/cmd/stack.isSvcRunning({0x103385828?, 0x140000560c0?}, 0x1400150a500?, {0x0?, 0x0?}, {0x1400150a500?, 0x0?}, {0x1033970c0?, 0x1400147a600?})
	github.com/okteto/okteto/pkg/cmd/stack/deploy.go:502 +0x34
github.com/okteto/okteto/pkg/cmd/stack.addDependentServices({0x103385828, 0x140000560c0}, 0x14001476240, {0x140000d9c80, 0x7, 0x8}, {0x1033970c0, 0x1400147a600})
	github.com/okteto/okteto/pkg/cmd/stack/deploy.go:883 +0x25c
github.com/okteto/okteto/pkg/cmd/stack.AddDependentServicesIfNotPresent({0x103385828?, 0x140000560c0?}, 0x7?, {0x140000d9c80?, 0x1400005ab90?, 0x46?}, {0x1033970c0?, 0x1400147a600?})
	github.com/okteto/okteto/pkg/cmd/stack/deploy.go:863 +0x34
github.com/okteto/okteto/cmd/deploy.setDeployOptionsValuesFromManifest({0x103385828, 0x140000560c0}, 0x140005d60d0, {0x140000520c4, 0x2b}, {0x1033970c0, 0x1400147a600})
	github.com/okteto/okteto/cmd/deploy/command_configuration.go:77 +0x3a0
github.com/okteto/okteto/cmd/deploy.(*DeployCommand).RunDeploy(0x140009b80e0, {0x103385828, 0x140000560c0}, 0x140005d60d0)
	github.com/okteto/okteto/cmd/deploy/deploy.go:291 +0x348
github.com/okteto/okteto/cmd/deploy.Deploy.func1.1()
	github.com/okteto/okteto/cmd/deploy/deploy.go:197 +0x68
created by github.com/okteto/okteto/cmd/deploy.Deploy.func1
	github.com/okteto/okteto/cmd/deploy/deploy.go:196 +0xa28
 x  Error executing command 'okteto deploy --file .okteto/docker-compose.yml --name cdp': exit status 2

hmyr@MBP-HMYR cdp % okteto version
okteto version 2.10.1
```

Upgrading the CLI version to latest did not help.

**To Reproduce**
Not clear.
We haven't changed anything in our deployment setup.

**Desktop (please complete the following information):**
- OS: macOS
- Version: 12.6.1
- Chip: Apple M1 Pro
- Memory: 16GB

**Comment by jLopezbarb** [comment]
Hi @hagaym, could you sjare you docker-compose without any sensible data? That would help us to debug the error

**Comment by hagaym** [comment]
Hi @jLopezbarb, unfortunately it is pretty much not possible.

However, I suspect that a typo in a "depends-on" reference is the root source... although it shouldn't lead to such a catastrophic error.
I will try to reproduce and update here.
