### ISSUE TITLE
Panic when running `okteto down` without original deployment

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [okteto/okteto#3388]
**Describe the bug**
When trying to run `okteto down` from an app that 
- has been deleted
- dev environment still exists
- dev environment uses a selector
the command panics

**To Reproduce**

1. `git clone https://github.com/okteto/go-getting-started` 
1. `cd go-getting-started`
1. `ok deploy`
1. `ok up`
2. `exit` from the dev container
3. `kubectl delete -f k8s.yml`
4. Modify the okteto.yml so that it starts with
    ```
    dev:
      hello-world:
        selector:
          dev.okteto.com/deployed-by: go-getting-started
    ```
1. `ok down`
5. See this error:
      ```
      panic: runtime error: index out of range [0] with length 0
      
      goroutine 1 [running]:
      github.com/okteto/okteto/pkg/k8s/deployments.GetByDev({0x2bc1e50, 0xc000128000}, 0xc001bebb00, {0xc000419608, 0x13}, {0x2bdaa50?, 0xc000e3db00?})
              github.com/okteto/okteto/pkg/k8s/deployments/crud.go:138 +0x42b
      github.com/okteto/okteto/pkg/k8s/apps.Get({0x2bc1e50, 0xc000128000}, 0xc001bebb00, {0xc000419608, 0x13}, {0x2bdaa50, 0xc000e3db00})
              github.com/okteto/okteto/pkg/k8s/apps/crud.go:32 +0x52
      github.com/okteto/okteto/cmd/utils.GetApp({0x2bc1e50, 0xc000128000}, 0xc001bebb00, {0x2bdaa50, 0xc000e3db00}, 0x0)
              github.com/okteto/okteto/cmd/utils/dev.go:384 +0x72
      github.com/okteto/okteto/cmd.Down.func1(0xc0017a8280?, {0xc00071f9c0, 0x1, 0x1?})
              github.com/okteto/okteto/cmd/down.go:103 +0x2fa
      github.com/spf13/cobra.(*Command).execute(0xc0017a8280, {0xc00071f9a0, 0x1, 0x1})
              github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
      github.com/spf13/cobra.(*Command).ExecuteC(0xc000737b80)
              github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
      github.com/spf13/cobra.(*Command).Execute(...)
              github.com/spf13/cobra@v1.5.0/command.go:918
      main.main()
              github.com/okteto/okteto/main.go:146 +0x9e9
    ```

**Expected behavior**
The behavior should be the same as when we don't use a selector, and it should return a clear error to the user like 
```
 x  Application 'hello-world' not found in namespace 't-agustinramirodiaz'
    Verify that your application is running and your okteto context is pointing to the right namespace
    Or set the 'autocreate' field in your okteto manifest if you want to create a standalone development container
    More information is available here: https://okteto.com/docs/reference/cli/#up

```
**Desktop (please complete the following information):**

- OS: linux mint
- Version 21

**Comment by andreafalzetti** [comment]
I'll pick this up for my onboarding as suggested 🙏
