### ISSUE TITLE
Getting started guide fails to run on Windows 10

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#344]
```
Provisioning your persistent volume...
 +  Persistent volume provisioned
  Starting the file synchronization service...
  Synchronizing your files...
  Overriding existing files in your Okteto environment...
 +  Files synchronized
  Activating your Okteto Environment...
 +  Okteto Environment activated
    Namespace: my-github-account
    Name:      vote
    Forward:   8080 -> 8080

 * Serving Flask app "app" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "app.py", line 53, in <module>
    extra_files=extra_files
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 1007, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
    sys.exit(reloader.restart_with_reloader())
  File "/usr/local/lib/python3.7/site-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
    exit_code = subprocess.call(args, env=new_environ, close_fds=False)
  File "/usr/local/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/src/app.py'

 x  Command execution failed

```

This happened to a user in Windows 10.

**Comment by rberrelleza** [comment]
This is fixed now.
