### ISSUE TITLE
Segmentation fault when deploying a malformed `docker-compose.yml`

### ISSUE THREAD

**Issue by andreafalzetti** [okteto/okteto#3440]
**Describe the bug**
A panic occurs when running `okteto deploy -f ./docker-compose.yml` on a malformed `docker-compose.yml`, example:

```yml
version: "3"

services:
  web:
    build: .
    ports:
      - 8080:8080
  another-service:

  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - 27017
    volumes:
      - mongodb-data:/bitnami/mongodb

volumes:
  mongodb-data:
```

Notice how `another-service:` is empty

**To Reproduce**

1. Clone https://github.com/okteto/go-api-docker-compose
1. Replace the `docker-compose.yml` with the one provided above
1. Run `okteto deploy -f ./docker-compose.yml`
1. Notice the panic error

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x478 pc=0x1011c3e18]

goroutine 30 [running]:
gopkg.in/yaml%2ev2.handleErr(0x14001887208)
	gopkg.in/yaml.v2@v2.4.0/yaml.go:249 +0x80
panic({0x102c8f3a0, 0x1047af330})
	runtime/panic.go:884 +0x204
github.com/okteto/okteto/pkg/model.validateExtensions({{0x104716cb8, 0x1}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, 0x140018758f0, 0x0, ...})
	github.com/okteto/okteto/pkg/model/stack_serializer.go:1627 +0x1c8
github.com/okteto/okteto/pkg/model.(*Stack).UnmarshalYAML(0x14000a5e600, 0x14001904160)
	github.com/okteto/okteto/pkg/model/stack_serializer.go:293 +0x7c
gopkg.in/yaml%2ev2.(*decoder).callUnmarshaler(0x140002e1920, 0x140018f8f50, {0x12cea2640, 0x14000a5e600})
	gopkg.in/yaml.v2@v2.4.0/decode.go:270 +0xa0
gopkg.in/yaml%2ev2.(*decoder).prepare(0x8?, 0x140018f8f50, {0x102f75b80?, 0x14000a5e600?, 0x1?})
	gopkg.in/yaml.v2@v2.4.0/decode.go:313 +0x260
gopkg.in/yaml%2ev2.(*decoder).unmarshal(0x140002e1920, 0x140018f8f50, {0x102f75b80?, 0x14000a5e600?, 0x14000100000?})
	gopkg.in/yaml.v2@v2.4.0/decode.go:364 +0x108
gopkg.in/yaml%2ev2.(*decoder).document(0x140018f8ee0?, 0x140018f8f50?, {0x102f75b80?, 0x14000a5e600?, 0x14001902600?})
	gopkg.in/yaml.v2@v2.4.0/decode.go:384 +0x7c
gopkg.in/yaml%2ev2.(*decoder).unmarshal(0x102de8d60?, 0x14000a5e600?, {0x102f75b80?, 0x14000a5e600?, 0x0?})
	gopkg.in/yaml.v2@v2.4.0/decode.go:360 +0x1ac
gopkg.in/yaml%2ev2.unmarshal({0x1400061b400, 0xed, 0x100}, {0x102de8d60?, 0x14000a5e600}, 0x1)
	gopkg.in/yaml.v2@v2.4.0/yaml.go:148 +0x3e0
gopkg.in/yaml%2ev2.UnmarshalStrict(...)
	gopkg.in/yaml.v2@v2.4.0/yaml.go:89
github.com/okteto/okteto/pkg/model.ReadStack({0x140015ffc00, 0xf0, 0x200}, 0x1)
	github.com/okteto/okteto/pkg/model/stack.go:312 +0xac
github.com/okteto/okteto/pkg/model.GetStackFromPath({0x0, 0x0}, {0x140015fd2c0, 0x41}, 0xe8?)
	github.com/okteto/okteto/pkg/model/stack.go:230 +0x1ac
github.com/okteto/okteto/pkg/model.getStack({0x0, 0x0}, {0x140015fd2c0, 0x41})
	github.com/okteto/okteto/pkg/model/stack.go:764 +0x12c
github.com/okteto/okteto/pkg/model.LoadStack({0x0, 0x0}, {0x1400187ff70?, 0x1, 0x140018878d8?}, 0x0)
	github.com/okteto/okteto/pkg/model/stack.go:727 +0x11c
github.com/okteto/okteto/pkg/model.getManifestFromFile({0x14000052044, 0x2e}, {0x140015fd2c0, 0x41})
	github.com/okteto/okteto/pkg/model/manifest.go:383 +0x390
github.com/okteto/okteto/pkg/model.getManifestFromDevFilePath({0x14000052044, 0x2e}, {0x1400044b200?, 0x0?})
	github.com/okteto/okteto/pkg/model/manifest.go:245 +0xe8
github.com/okteto/okteto/pkg/model.GetManifestV2({0x1400044b200, 0x12})
	github.com/okteto/okteto/pkg/model/manifest.go:288 +0x3c
github.com/okteto/okteto/cmd/deploy.(*DeployCommand).RunDeploy(0x1400078f800, {0x1030b3c08, 0x14000122000}, 0x1400159e5b0)
	github.com/okteto/okteto/cmd/deploy/deploy.go:302 +0x238
github.com/okteto/okteto/cmd/deploy.Deploy.func1.1()
	github.com/okteto/okteto/cmd/deploy/deploy.go:206 +0x64
created by github.com/okteto/okteto/cmd/deploy.Deploy.func1
	github.com/okteto/okteto/cmd/deploy/deploy.go:205 +0xa20
```

**Expected behavior**
The CLI should fail gracefully similar to:

```
 x  Invalid manifest:
Unmarshal error: 'yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `XXX` into model.devType'
```

**Comment by Abhishek-569** [comment]
I want to work on this issue.

**Comment by andreafalzetti** [comment]
@Abhishek-569 feel free to pick this up 🙏

**Comment by Abhishek-569** [comment]
Thank you. I have reproduced this issue in my local setup. Where do in this repo we valid the YAML manifest?

**Comment by andreafalzetti** [comment]
Removing you for now, @Abhishek-569 - let me know if you have time in the future and I will assign it to you again, thanks!

**Comment by AnshulAngaria** [comment]
Hey @andreafalzetti @pchico83 , I can take this up.

**Comment by jLopezbarb** [comment]
> Hey @andreafalzetti @pchico83 , I can take this up.

Hi @AnshulAngaria I've assigned it to you. Let us know if you need more context or any help with the issue 😃

**Comment by AnshulAngaria** [comment]
@andreafalzetti @jLopezbarb, Raised the PR, Please review.
