### ISSUE TITLE
Unable to connect to remote machine

### ISSUE THREAD

**Issue by snowman2** [okteto/okteto#3459]
**Describe the bug**
Not able to connect to the remote machine.

Docker images I have tried:
- okteto/python:3
- ubuntu:22.04
- public.ecr.aws/lambda/python:3.9

Note: It works with an older image based on Ubuntu 22 I created a while back. Not sure why these don't work.

**To Reproduce**
Run "Okteto Up" in vscode

**Expected behavior**
It should work.

**Desktop (please complete the following information):**

VSCode information:
```
Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:25.715Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.19.0-35-generic
```
OS & Version: Ubuntu 22.04

**Additional context**
```yaml
dev:
  my-setup-dev: 
    image: okteto/python:3
    autocreate: true
    workdir: /okteto
    sync:
      - .:/okteto
    forward:
      - 8000:8000
    command: bash
    resources:
      limits:
        memory: "4Gi"
        cpu: "1"
    persistentVolume:
      enabled: false
```

Remote SSH logs:
```
[09:57:44.194] SSH Resolver called for "ssh-remote+my-setup-dev.okteto", attempt 5, (Reconnection)
[09:57:44.196] SSH Resolver called for host: my-setup-dev.okteto
[09:57:44.196] Setting up SSH remote "my-setup-dev.okteto"
[09:57:44.197] Acquiring local install lock: /tmp/vscode-remote-ssh-e2eeb418-install.lock
[09:57:44.199] Looking for existing server data file at ~/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-e2eeb418-e4503b30fc78200f846c62cf8091b76ff5547662-0.84.0/data.json
[09:57:44.200] Using commit id "e4503b30fc78200f846c62cf8091b76ff5547662" and quality "stable" for server
[09:57:44.204] Install and start server if needed
[09:57:44.208] askpass server listening on /run/user/1000/vscode-ssh-askpass-95894f1a1335d4046e187073eae593112c9c4f3a.sock
[09:57:44.208] Spawning local server with {"serverId":5,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-de4ac2f9dae6a683bb5d84b52473cb71ce4452d9.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","35777","-o","ConnectTimeout=15","my-setup-dev.okteto"],"serverDataFolderName":".vscode-server","dataFilePath":"~/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-e2eeb418-e4503b30fc78200f846c62cf8091b76ff5547662-0.84.0/data.json"}
[09:57:44.208] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","SHELL":"/bin/bash","DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"~/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"~/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-95894f1a1335d4046e187073eae593112c9c4f3a.sock"}
[09:57:44.214] Spawned 25886
[09:57:44.357] > local-server-5> Spawned ssh, pid=25894
[09:57:44.362] stderr> OpenSSH_8.9p1 Ubuntu-3ubuntu0.1, OpenSSL 3.0.2 15 Mar 2022
[09:57:44.363] stderr> ssh: connect to host 0.0.0.0 port 22106: Connection refused
[09:57:44.364] > local-server-5> ssh child died, shutting down
[09:57:44.371] Local server exit: 0
[09:57:44.371] Received install output: local-server-5> Spawned ssh, pid=25894
OpenSSH_8.9p1 Ubuntu-3ubuntu0.1, OpenSSL 3.0.2 15 Mar 2022
ssh: connect to host 0.0.0.0 port 22106: Connection refused
local-server-5> ssh child died, shutting down

[09:57:44.372] Failed to parse remote port from server output
[09:57:44.372] Resolver error: Error: 
	at Function.Create (~/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585222)
	at Object.t.handleInstallOutput (~/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:583874)
	at Object.e [as tryInstallWithLocalServer] (~/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:624373)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async ~/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:643506
	at async Object.t.withShowDetailsEvent (~/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:647224)
	at async ~/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622845
	at async T (~/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:619351)
	at async Object.t.resolveWithLocalServer (~/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622460)
	at async Object.t.resolve (~/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644834)
	at async ~/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
[09:57:44.377] ------
```

**Comment by snowman2** [comment]
This is the extension: https://marketplace.visualstudio.com/items?itemName=okteto.remote-kubernetes

Looks like maybe I should open the issue here?

https://github.com/okteto/remote-kubernetes

**Comment by snowman2** [comment]
Possibly related: https://github.com/okteto/remote-kubernetes/issues/199
