### ISSUE TITLE
Panic executing `okteto destroy --remote` when there is no okteto manifest

### ISSUE THREAD

**Issue by ifbyol** [okteto/okteto#3656]
**Describe the bug**

I was able to deploy my repository using `okteto deploy --remote` but when I executed `okteto destroy --remote` I got a panic

```
╰─ okteto destroy --remote
 i  Using test-nacho @ okteto.mario18rc.dev.okteto.net as context
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2c43057]

goroutine 1 [running]:
github.com/okteto/okteto/cmd/destroy.newRemoteDestroyer(0xc001c74000)
	github.com/okteto/okteto/cmd/destroy/remote.go:104 +0x217
github.com/okteto/okteto/cmd/destroy.(*destroyCommand).getDestroyer(0xc001a3fbc0, {0x3b54878, 0xc0001a0000}, 0xc0001e5880)
	github.com/okteto/okteto/cmd/destroy/destroy.go:269 +0x345
github.com/okteto/okteto/cmd/destroy.Destroy.func1(0xc001862f00?, {0xc00184c840?, 0x0?, 0x1?})
	github.com/okteto/okteto/cmd/destroy/destroy.go:193 +0x990
github.com/spf13/cobra.(*Command).execute(0xc001862f00, {0xc00184c830, 0x1, 0x1})
	github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc001848780)
	github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
	github.com/okteto/okteto/main.go:148 +0xa25
```

I think the error might come from the fact I'm not having an `okteto.yml` file in my root folder. Instead, I have a `k8s.yml` file.

The repository is https://github.com/ifbyol/test-pipeline and the branch `destroy-custom-manifest`

**To Reproduce**

1. Clone the repository https://github.com/ifbyol/test-pipeline
2. Change to the branch `destroy-custom-manifest`
3. Execute `okteto deploy --remote`. You should see how the application is successfully deployed
4. Execute `okteto destroy --remote`. You should see the panic error

**Expected behavior**

As I was able to deploy the application correctly, I would expect to be able to destroy it successfully. If something is wrong, I would expect a clear error message instead of a stack trace

**Desktop (please complete the following information):**

- Version: `2.15.3` and master

**Additional context**
N/A

**Comment by nitishfy** [comment]
**Update:** I think there's a need to refactor the `destroy` code to match with `deploy`code. I've done it locally and there is a need for improvement. I think raising a draft PR for this issue will work meanwhile. 
cc @pchico83

**Comment by nitishfy** [comment]
**Update:** We're ready to review the above PR now.
