### ISSUE TITLE
Panic when using `build.<item>.name`

### ISSUE THREAD

**Issue by andreafalzetti** [okteto/okteto#3708]
**Describe the bug**
The `name` property of the Build section is not documented but it [exists in the manifest parser](https://github.com/okteto/okteto/blob/master/pkg/model/dev.go#L124). If used, it could lead to a panic.

If `name` is set to the same name as the image, it panics. If the name is different, it returns a misleading error.

**To Reproduce the panic**
1. Using the following manifest, run `okteto build -l=debug`
```yaml
DEBU[0000] server name override: ""
INFO[0000] started okteto build -l=debug
INFO[0000] context will load from /Users/andrea/dev/okteto/k8s-status-api/okteto.yml
INFO[0000] Found okteto manifest file on path: /Users/andrea/dev/okteto/k8s-status-api/okteto.yml
INFO[0000] found repository url git@github.com:andreafalzetti/k8s-status-api.git
INFO[0000] found '0' configmaps in the namespace default
INFO[0000] inferring name from git repository URL
INFO[0000] Images to build: [k8s-status-api]
INFO[0000] Building image for service 'k8s-status-api'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x102926c20]

goroutine 1 [running]:
github.com/okteto/okteto/pkg/filesystem.FileExistsAndNotDir({0x140005c87e0?, 0x103ee7b58?})
	github.com/okteto/okteto/pkg/filesystem/file.go:76 +0x60
github.com/okteto/okteto/pkg/cmd/build.extractFromContextAndDockerfile({0x1400052bdd0, 0xe}, {0x1040b963c, 0xa}, {0x1400052bdb0, 0xe})
	github.com/okteto/okteto/pkg/cmd/build/build.go:361 +0xa0
github.com/okteto/okteto/pkg/cmd/build.OptsFromBuildInfo({0x140005d629e?, 0x140005be0f0?}, {0x1400052bdb0, 0xe}, 0x140005c4d00, 0xe?, {0x12df2fa78?, 0x14000630280})
	github.com/okteto/okteto/pkg/cmd/build/build.go:283 +0x380
github.com/okteto/okteto/cmd/build/v2.(*OktetoBuilder).buildSvcFromDockerfile(0x1400032a000, {0x1050a4718, 0x1400019a000}, 0x140017a0300, {0x1400052bdb0, 0xe}, 0x14001501d40)
	github.com/okteto/okteto/cmd/build/v2/build.go:247 +0x270
github.com/okteto/okteto/cmd/build/v2.(*OktetoBuilder).buildService(0x104d537e0?, {0x1050a4718, 0x1400019a000}, 0x140017a0300, {0x1400052bdb0, 0xe}, 0x27?)
	github.com/okteto/okteto/cmd/build/v2/build.go:224 +0xa8
github.com/okteto/okteto/cmd/build/v2.(*OktetoBuilder).Build(0x1400032a000, {0x1050a4718, 0x1400019a000}, 0x14001501d40)
	github.com/okteto/okteto/cmd/build/v2/build.go:184 +0x864
github.com/okteto/okteto/cmd/build.Build.func1(0x140015cb680?, {0x140015d04c0?, 0x1?, 0x1?})
	github.com/okteto/okteto/cmd/build/command.go:106 +0x2f4
github.com/spf13/cobra.(*Command).execute(0x140015cb680, {0x140015d04b0, 0x1, 0x1})
	github.com/spf13/cobra@v1.5.0/command.go:872 +0x4d0
github.com/spf13/cobra.(*Command).ExecuteC(0x14001394000)
	github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
	github.com/okteto/okteto/main.go:153 +0x76c
```

**To Reproduce the error (no panic)**
1. Using the following manifest, run `okteto build -l=debug`
```yaml
build:
  k8s-status-api:
    name: test
    image: okteto.dev/k8s-status-api:1.0.0
    context: .
```

Output:
```
DEBU[0000] server name override: ""
INFO[0000] started okteto build -l=debug
INFO[0000] context will load from /Users/andrea/dev/okteto/k8s-status-api/okteto.yml
INFO[0000] Found okteto manifest file on path: /Users/andrea/dev/okteto/k8s-status-api/okteto.yml
INFO[0000] found repository url git@github.com:andreafalzetti/k8s-status-api.git
INFO[0000] found '0' configmaps in the namespace default
INFO[0000] inferring name from git repository URL
INFO[0000] Images to build: [k8s-status-api]
INFO[0000] Building image for service 'k8s-status-api'
INFO[0000] Build 'k8s-status-api': Dockerfile 'Dockerfile' is not in a relative path to context 'test'
 !  Build 'k8s-status-api': Dockerfile 'Dockerfile' is not in a relative path to context 'test'
INFO[0000] error on CheckIfDirectory: stat test: no such file or directory
INFO[0000] Error building service 'k8s-status-api': invalid build context: 'test' does not exist
 x  Error building service 'k8s-status-api': invalid build context: 'test' does not exist
```

**Expected behavior**
The CLI should handle errors gracefully and return appropriate error messages

**Comment by andreafalzetti** [comment]
Closing as we are planning to deprecate this property, see discussion: https://okteto.slack.com/archives/C044FNE5B4Z/p1686566588008659
