### ISSUE TITLE
Panic when deployment has more than one container and the container is not specified in the manifest

### ISSUE THREAD

**Issue by rberrelleza** [okteto/okteto#728]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2026c9f]
goroutine 35 [running]:
github.com/okteto/okteto/pkg/k8s/deployments.TranslateDevContainer(0x0, 0xc0016e4d00)
    /home/circleci/project/pkg/k8s/deployments/translate.go:180 +0x6f
github.com/okteto/okteto/pkg/k8s/deployments.translate(0xc00009e840, 0xc0015862c0, 0xc0003e2420, 0x0, 0x0)
    /home/circleci/project/pkg/k8s/deployments/translate.go:102 +0x65e
github.com/okteto/okteto/pkg/k8s/deployments.TranslateDevMode(0xc001583d40, 0xc0015862c0, 0xc0003e2420, 0xc001583d40, 0x0)
    /home/circleci/project/pkg/k8s/deployments/crud.go:180 +0xb8
github.com/okteto/okteto/cmd.(*UpContext).devMode(0xc00151e090, 0xc0015c8900, 0x0, 0x0, 0x0)
    /home/circleci/project/cmd/up.go:408 +0x3f4
github.com/okteto/okteto/cmd.(*UpContext).Activate(0xc00151e090, 0x0)
    /home/circleci/project/cmd/up.go:248 +0x353
created by github.com/okteto/okteto/cmd.RunUp
    /home/circleci/project/cmd/up.go:167 +0x1cb
```

**Comment by rberrelleza** [comment]
happens in okteto 1.7.4
